
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "ronaldo",
  "email": "ronaldo@gmail.com"
}

###

POST http://localhost:3333/surveys
Content-Type: application/json

{
  "title": "Deslike",
  "description": "Conteúdo top2"
}

###

GET http://localhost:3333/surveys
Content-Type: application/json

###


POST http://localhost:3333/send-mail
Content-Type: application/json

{
  "email": "ronaldo@gmail.com",
  "survey_id": "922d9e80-6449-4526-99e1-e51c51e92cb7"
}

###