
POST http://localhost:3333/users
Content-Type: application/json

{
  "name": "ronaldo",
  "email": "ronaldo@gmail.com"
}

###

POST http://localhost:3333/surveys
Content-Type: application/json

{
  "title": "Deslike",
  "description": "Conteúdo top2"
}

###

GET http://localhost:3333/surveys
Content-Type: application/json

###


GET http://localhost:3333/send-mail
Content-Type: application/json

{
  "email": "ronaldo@gmail.com",
  "survey_id": "0ea2feff-0d4a-48d5-b938-1ffee35ed02e"
}

###